apiVersion: jenkins.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  labels:
    env: dev
    team: jx
  name: dev
spec:
  kind: Development
  label: Development
  namespace: jx
  previewGitInfo:
    user: {}
  promotionStrategy: Never
  source:
    ref: master
    url: https://github.com/cb-kubecd/environment-pr-499-3-gitops-gkebdd-dev.git
  teamSettings:
    appsRepository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
    buildPackRef: master
    buildPackUrl: https://github.com/jenkins-x-buildpacks/jenkins-x-kubernetes.git
    defaultScheduler:
      kind: ""
      name: ""
    dockerRegistryOrg: jenkins-x-bdd3
    envOrganisation: cb-kubecd
    gitServer: https://github.com
    helmTemplate: true
    importMode: Jenkinsfile
    kubeProvider: gke
    pipelineUsername: jenkins-x-bot-test
    promotionEngine: Jenkins
    prowConfig: Legacy
    prowEngine: Tekton
    quickstartLocations:
    - excludes:
      - WIP-*
      gitKind: github
      gitUrl: https://github.com
      includes:
      - '*'
      owner: jenkins-x-quickstarts
    useGitOps: true
    versionStreamRef: f04d40a4a432b0b662e58ecc52a4d2647cf29541
    versionStreamUrl: https://github.com/jenkins-x/jenkins-x-versions.git
status: {}
